### ISSUE TITLE
AWS Shim fails to load AWS lib loader when vendored

### ISSUE THREAD

**Issue by clintoncwolfe** [chef/inspec-aws#138] opened 2017-12-14 20:10 UTC
@aaronlippold reporter

To reproduce:

1. Make simple profile.
2. Add a dependency in inspec.yml 
```
depends:
  - name: aws
    git: https://github.com/chef/inspec-aws.git
```
3. Vendor the deps using `inspec vendor`.
4. Try to run the profile.  `inspec exec .`

```
libraries/aws_aaa_shim.rb:3:in `require_relative': cannot load such file -- /Users/cwolfe/sandbox/inspec/aws-test-profiles/adhoc/lib/inspec/aws (LoadError)
	from libraries/aws_aaa_shim.rb:3:in `load_with_context'
```

**Comment by clintoncwolfe** [comment] 2017-12-15 03:27
Well, the require_relative is not likely to ever succeed.  inspec core reads each library file (here, aws_aaa_shim.rb) and then evals it separately - see https://github.com/chef/inspec/blob/master/lib/inspec/profile_context.rb#L126 and https://github.com/chef/inspec/blob/master/lib/inspec/library_eval_context.rb .  The `instance_eval(String)` breaks require_relative; and we can't guess the true path to the file, because we might be in the cache, or we might be vendored with a hashed directory name that will change.

This will go away when we merge into inspec-core, since we won't need a shim at all.

Options at this point are to move the supporting libraries back to the `libraries/` directory, or try more metaprogramming shenanigans to try to determine the proper location to load.

**Comment by aaronlippold** [comment] 2017-12-23 14:15
This is still causing issues on system - OSX mostly - and need to be reexamined.

**Comment by arlimus** [comment] 2017-12-29 16:59
This issue is caused by a problem in chaining `require` calls in inspec. when we call it the first time in a library, it is loaded with all the wonderful inspec loader mechanics that find the files in the libraries folder no matter if its in a zip or tar or filesystem or your closet. But, as soon as that thing finishes, we load its contents in a regular eval, and that doesn't carry the wonderful land of independent loading anymore, and instead just does ruby loading - which in this case leads to a flat dive onto its face.

```
# Main AWS loader file.  The intent is for this to be
# loaded only if AWS resources are needed.

require 'aws-sdk' # TODO: split once ADK v3 is in use
binding.pry
require '_aws_backend_factory_mixin'
# ...
```

```
[1] pry(main)> show-source require
Error: Cannot locate this method: require. Invoke the 'gem-install pry-doc' Pry command to get access to Ruby Core documentation.
```

**Comment by arlimus** [comment] 2017-12-29 19:48
Will be targeted: https://github.com/chef/inspec/pull/2428

**Comment by arlimus** [comment] 2018-01-02 20:47
Now that 2428 is merged

**Closed** 2018-02-09 16:22 UTC
Labels: aws, bug
